### ISSUE TITLE
A few obstacles I need some help with...

### ISSUE THREAD

**Issue by yooohana** [financialforcedev/alexa-salesforce-flow-skill#1]
**1. Issue with enabling SSML/getting the speech output right**

The skill I've built tells you your calendar for any given date. But Alexa pronounces the times literally, so for “10:00” she goes “ten colon zero zero”. i have been looking into ssml to hopefully smooth that out as well. however, when i assign the “alexa_tell” variable a ssml formatted response, the code doesn’t seem to pick up on it and the type of the speech output object remains plain text.

**2. Changing the Speech output for an onLaunch request**

I would like to give the user an overview of what the skill can do instead of the standard output "I will run salesforce flow" when the skill is launched without a specific intent request. I changed only the string in the code, created a zip-file out of the same files as before and uploaded to aws lambda. however, the execution now fails with the following error: 
`Syntax error in module 'index': SyntaxError
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/var/task/index.js:41:18)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)`

Any idea why that is?

**3. Including cards in my response**

For one intent I'd like to include a card that displays info about an open lead (first & last name, phone number). Any tips on how to make that happen?

Thank you so much for taking the time to have a look at these. Very much appreciated!

**Comment by yooohana** [comment]
I have actually figured out number 1 and 2, so the only thing i need help with is how to include cards in the response. thanks!

**Comment by afawcett** [comment]
Thanks @yooohana. I have marked this as an enhancement, sounds fun! Probably will require some new flow variable names to be agreed and then the node code can respond accordingly. Meanwhile can you share how you solve 1 and 2?
